#ARDUINO_QUIET = 0

ARD_DIR = $(HOME)/programs/arduino

ARDUINO_DIR = $(ARD_DIR)/1.8.2
ARDMK_DIR = $(ARD_DIR)/Arduino-Makefile
AVR_TOOLS_DIR = $(ARDUINO_DIR)/hardware/tools/avr

BOARD_TAG = mega
BOARD_SUB = atmega2560
MONITOR_PORT = /dev/arduino

MONITOR_CMD = picocom
MONITOR_PARAMS = -e m

ARDUINO_SKETCHBOOK = $(HOME)/arduino
USER_LIB_PATH = $(ARDUINO_SKETCHBOOK)/libraries
ARDUINO_LIBS_PATH = $(ARDUINO_DIR)/libraries

include $(ARDMK_DIR)/Arduino.mk
